name: CI
on:
  push:
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: coverage run tests/

      - name: Tests report
        run: coverage report